version: "3"
services:
  nginx:
    container_name: nginx_project_xxxx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    container_name: php_project_xxxx
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid: 1000
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    expose:
      - "9000"
#  mysql:
#    image: 'mysql/mysql-server:8.0'
#    container_name: 'db_project_xxxx'
#    ports:
#        - '${FORWARD_DB_PORT:-3306}:3306'
#    environment:
#        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#        MYSQL_ROOT_HOST: "%"
#        MYSQL_DATABASE: '${DB_DATABASE}'
#        MYSQL_USER: '${DB_USERNAME}'
#        MYSQL_PASSWORD: '${DB_PASSWORD}'
#        MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    volumes:
#        - 'db-data-projetc-xxxx:/var/lib/mysql'
#        # - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#    networks:
#        - internal
#    healthcheck:
#        test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
#        retries: 3
#        timeout: 5s
networks:
  internal:
    driver: bridge
volumes:
  db-data-projetc-xxxx:
    driver: local