version: "3"
services:
  nginx_project_xxx:
    container_name: nginx_project_xxxx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./storage/logs/nginx:/var/log/nginx/
  php_project_xxx:
    container_name: php_project_xxxx
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid: 1000
        APP_ENV: ${APP_ENV}
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./storage/logs/php.log:/var/log/fpm-php.www.log
    depends_on:
      - redis
    expose:
      - "9000"
  #  horizon:
  #    build:
  #      context: ./docker/php
  #      dockerfile: Dockerfile
  #      args:
  #        user: ${USER}
  #        uid: 1000
  #    container_name: horizon
  #    command: php artisan horizon
  #    volumes:
  #      - ./:/var/www/html/
  #    depends_on:
  #      - php_project_xxx
  #      - nginx_project_xxx
  #      - redis
  #    networks:
  #      - internal
  redis:
    image: redis
    command: redis-server
    #    hostname: redis.project-x.test
    container_name: redis_project_xxxx
    tty: true
    restart: on-failure
    networks:
      - internal
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    container_name: minio_project_xxxx
    #restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminadmin"
      MINIO_DEFAULT_BUCKETS: "projectbucket"
    volumes:
      - minio-data-projetc-xxxx:/data
    command: server --console-address ":9001" /data
    networks:
      - internal
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: 'db_project_xxx'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'db-data-projetc-xxxx:/var/lib/mysql'
    networks:
      - internal
networks:
  internal:
    driver: bridge
volumes:
  db-data-projetc-xxxx:
    driver: local
  minio-data-projetc-xxxx:
    driver: local